/*
  # Insert initial word data

  1. Data
    - Insert curated word lists across different categories
    - Include difficulty levels for balanced gameplay
    - Cover animals, objects, food, actions, nature categories
*/

-- Insert animals
INSERT INTO words (word, difficulty, category) VALUES
  ('cat', 'easy', 'animals'),
  ('dog', 'easy', 'animals'),
  ('elephant', 'medium', 'animals'),
  ('giraffe', 'medium', 'animals'),
  ('lion', 'easy', 'animals'),
  ('tiger', 'easy', 'animals'),
  ('bear', 'easy', 'animals'),
  ('rabbit', 'easy', 'animals'),
  ('horse', 'easy', 'animals'),
  ('cow', 'easy', 'animals'),
  ('pig', 'easy', 'animals'),
  ('sheep', 'easy', 'animals'),
  ('chicken', 'easy', 'animals'),
  ('duck', 'easy', 'animals'),
  ('fish', 'easy', 'animals'),
  ('shark', 'medium', 'animals'),
  ('whale', 'medium', 'animals'),
  ('dolphin', 'medium', 'animals'),
  ('octopus', 'hard', 'animals'),
  ('butterfly', 'medium', 'animals'),
  ('bee', 'easy', 'animals'),
  ('spider', 'easy', 'animals'),
  ('snake', 'easy', 'animals'),
  ('frog', 'easy', 'animals'),
  ('turtle', 'medium', 'animals'),
  ('penguin', 'medium', 'animals'),
  ('owl', 'easy', 'animals'),
  ('eagle', 'medium', 'animals'),
  ('parrot', 'medium', 'animals'),
  ('flamingo', 'hard', 'animals')
ON CONFLICT (word) DO NOTHING;

-- Insert objects
INSERT INTO words (word, difficulty, category) VALUES
  ('car', 'easy', 'objects'),
  ('house', 'easy', 'objects'),
  ('tree', 'easy', 'objects'),
  ('flower', 'easy', 'objects'),
  ('book', 'easy', 'objects'),
  ('phone', 'easy', 'objects'),
  ('computer', 'medium', 'objects'),
  ('chair', 'easy', 'objects'),
  ('table', 'easy', 'objects'),
  ('lamp', 'easy', 'objects'),
  ('clock', 'easy', 'objects'),
  ('key', 'easy', 'objects'),
  ('door', 'easy', 'objects'),
  ('window', 'easy', 'objects'),
  ('mirror', 'easy', 'objects'),
  ('camera', 'medium', 'objects'),
  ('guitar', 'medium', 'objects'),
  ('piano', 'medium', 'objects'),
  ('bicycle', 'medium', 'objects'),
  ('airplane', 'medium', 'objects'),
  ('boat', 'easy', 'objects'),
  ('train', 'easy', 'objects'),
  ('bus', 'easy', 'objects'),
  ('umbrella', 'medium', 'objects'),
  ('hat', 'easy', 'objects'),
  ('shoes', 'easy', 'objects'),
  ('glasses', 'easy', 'objects'),
  ('watch', 'easy', 'objects'),
  ('ring', 'easy', 'objects'),
  ('necklace', 'medium', 'objects')
ON CONFLICT (word) DO NOTHING;

-- Insert food
INSERT INTO words (word, difficulty, category) VALUES
  ('pizza', 'easy', 'food'),
  ('burger', 'easy', 'food'),
  ('cake', 'easy', 'food'),
  ('ice cream', 'easy', 'food'),
  ('apple', 'easy', 'food'),
  ('banana', 'easy', 'food'),
  ('orange', 'easy', 'food'),
  ('strawberry', 'medium', 'food'),
  ('grape', 'easy', 'food'),
  ('watermelon', 'medium', 'food'),
  ('bread', 'easy', 'food'),
  ('cheese', 'easy', 'food'),
  ('milk', 'easy', 'food'),
  ('coffee', 'easy', 'food'),
  ('tea', 'easy', 'food'),
  ('water', 'easy', 'food'),
  ('juice', 'easy', 'food'),
  ('sandwich', 'easy', 'food'),
  ('pasta', 'easy', 'food'),
  ('rice', 'easy', 'food'),
  ('chicken', 'easy', 'food'),
  ('fish', 'easy', 'food'),
  ('egg', 'easy', 'food'),
  ('salad', 'easy', 'food'),
  ('soup', 'easy', 'food'),
  ('cookie', 'easy', 'food'),
  ('chocolate', 'medium', 'food'),
  ('candy', 'easy', 'food'),
  ('donut', 'easy', 'food'),
  ('pancake', 'medium', 'food')
ON CONFLICT (word) DO NOTHING;

-- Insert actions
INSERT INTO words (word, difficulty, category) VALUES
  ('running', 'easy', 'actions'),
  ('jumping', 'easy', 'actions'),
  ('dancing', 'medium', 'actions'),
  ('singing', 'medium', 'actions'),
  ('reading', 'easy', 'actions'),
  ('writing', 'easy', 'actions'),
  ('drawing', 'easy', 'actions'),
  ('painting', 'medium', 'actions'),
  ('cooking', 'easy', 'actions'),
  ('eating', 'easy', 'actions'),
  ('sleeping', 'easy', 'actions'),
  ('walking', 'easy', 'actions'),
  ('swimming', 'medium', 'actions'),
  ('flying', 'easy', 'actions'),
  ('driving', 'easy', 'actions'),
  ('climbing', 'medium', 'actions'),
  ('falling', 'easy', 'actions'),
  ('laughing', 'medium', 'actions'),
  ('crying', 'easy', 'actions'),
  ('smiling', 'easy', 'actions'),
  ('waving', 'easy', 'actions'),
  ('clapping', 'easy', 'actions'),
  ('pointing', 'easy', 'actions'),
  ('thinking', 'medium', 'actions'),
  ('dreaming', 'medium', 'actions'),
  ('playing', 'easy', 'actions'),
  ('working', 'easy', 'actions'),
  ('studying', 'medium', 'actions'),
  ('teaching', 'medium', 'actions'),
  ('learning', 'medium', 'actions')
ON CONFLICT (word) DO NOTHING;

-- Insert nature
INSERT INTO words (word, difficulty, category) VALUES
  ('sun', 'easy', 'nature'),
  ('moon', 'easy', 'nature'),
  ('star', 'easy', 'nature'),
  ('cloud', 'easy', 'nature'),
  ('rain', 'easy', 'nature'),
  ('snow', 'easy', 'nature'),
  ('wind', 'medium', 'nature'),
  ('fire', 'easy', 'nature'),
  ('water', 'easy', 'nature'),
  ('earth', 'easy', 'nature'),
  ('mountain', 'medium', 'nature'),
  ('river', 'easy', 'nature'),
  ('ocean', 'easy', 'nature'),
  ('forest', 'medium', 'nature'),
  ('desert', 'medium', 'nature'),
  ('island', 'medium', 'nature'),
  ('volcano', 'hard', 'nature'),
  ('rainbow', 'medium', 'nature'),
  ('lightning', 'hard', 'nature'),
  ('thunder', 'medium', 'nature'),
  ('beach', 'easy', 'nature'),
  ('cave', 'easy', 'nature'),
  ('valley', 'medium', 'nature'),
  ('hill', 'easy', 'nature'),
  ('lake', 'easy', 'nature'),
  ('pond', 'easy', 'nature'),
  ('stream', 'medium', 'nature'),
  ('waterfall', 'hard', 'nature'),
  ('rock', 'easy', 'nature'),
  ('stone', 'easy', 'nature')
ON CONFLICT (word) DO NOTHING;